import api from './api';

/**
 * Staff Service
 * Handles all API calls related to staff management
 * All endpoints require MANAGER role on the backend
 */

/**
 * Get all staff with optional filters
 * @param {Object} params - Query parameters
 * @param {string} params.search - Search keyword (searches name and email)
 * @param {string} params.role - Filter by role (MANAGER, STAFF)
 * @param {string} params.department - Filter by department
 * @param {boolean} params.active - Filter by active status
 * @returns {Promise<Array>} List of staff members
 */
export const getStaff = async (params = {}) => {
    const response = await api.get('/staff', { params });
    return response.data;
};

/**
 * Create a new staff member
 * Password is auto-generated by backend and emailed to the user
 * @param {Object} data - Staff data
 * @param {string} data.email - Staff email address
 * @param {string} data.name - Staff full name
 * @param {string} data.department - Department name
 * @returns {Promise<Object>} Created staff member
 */
export const createStaff = async (data) => {
    const response = await api.post('/staff', data);
    return response.data;
};

/**
 * Update an existing staff member
 * Email cannot be changed, only name and department
 * @param {number} id - Staff ID
 * @param {Object} data - Updated staff data
 * @param {string} data.name - Staff full name
 * @param {string} data.department - Department name
 * @returns {Promise<Object>} Updated staff member
 */
export const updateStaff = async (id, data) => {
    const response = await api.put(`/staff/${id}`, data);
    return response.data;
};

/**
 * Activate a staff member's account
 * @param {number} id - Staff ID
 * @returns {Promise<Object>} Updated staff member
 */
export const activateStaff = async (id) => {
    const response = await api.patch(`/staff/${id}/activate`);
    return response.data;
};

/**
 * Deactivate a staff member's account
 * Backend prevents self-deactivation (returns 409 Conflict)
 * @param {number} id - Staff ID
 * @returns {Promise<Object>} Updated staff member
 */
export const deactivateStaff = async (id) => {
    const response = await api.patch(`/staff/${id}/deactivate`);
    return response.data;
};

/**
 * Manually unlock a locked staff account
 * Clears failedAttempts and lockUntil fields
 * Manager-only endpoint
 * @param {number} id - Staff ID
 * @returns {Promise<void>}
 */
export const unlockStaff = async (id) => {
    await api.patch(`/staff/${id}/unlock`);
};
