package com.roomify.backend.entity;

public enum NotificationEventType {
    SERVICE_REQUEST_CREATED,
    PAYMENT_INCOMPLETE,
    PAYMENT_FAILED,
    RESERVATION_CREATED,
    RESERVATION_CANCELLED,
    PAYMENT_COMPLETED,
    CHECKIN_REMINDER,
    ROOM_READY,
    SERVICE_REQUEST_COMPLETED,
    EMAIL_DELIVERY_FAILED,
    PASSWORD_RESET
}
